" two space tab industry standard
set tabstop=2
set expandtab

" auto indent in functions
set shiftwidth=2

" syntax highlighting
syntax on

" highlight word search and unhighlight on (\)
set hlsearch
set incsearch
set ignorecase
set smartcase
nnoremap \ :noh<return>

" show matching parentheses / brackets
set showmatch

" toggle code folds with space
nnoremap <space> :call ToggleFolds()<CR>
set foldmethod=indent
set nofoldenable
let $foldOn=0
function ToggleFolds()
  if $foldOn==1
    :exe "normal zR"
    let $foldOn=0
  else
    :exe "normal zM"
    let $foldOn=1
  endif
endfunction

" no wrapped line skip
nmap j gj
nmap k gk

" memory configuration
set viminfo='100,<1000,s100,h

" nice color scheme
color elflord
